name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx6G -Xss4M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx6G -Xss4M # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)
  NODE_OPTIONS: --max_old_space_size=6144

on:
  pull_request:
  push:
    branches:
      - 'series/2.x'
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.2
    - name: Setup Java
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 17
        check-latest: true
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Install libuv
      run: sudo apt-get update && sudo apt-get install -y libuv1-dev
    - name: Lint code
      run: ./sbt check

  compile:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.11.*', '2.12.*', '2.13.*', '3.*']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 7
      - name: Test/compile 2.11
        if: ${{ startsWith(matrix.scala, '2.11.') }}
        run: free --si -tmws 10 & ./sbt ++${{ matrix.scala }} root211/Test/compile
      - name: Test/compile 2.12
        if: ${{ startsWith(matrix.scala, '2.12.') }}
        run: free --si -tmws 10 & ./sbt ++${{ matrix.scala }} root212/Test/compile
      - name: Test/compile 2.13
        if: ${{ startsWith(matrix.scala, '2.13.') }}
        run: free --si -tmws 10 & ./sbt ++${{ matrix.scala }} root213/Test/compile
      - name: Test/compile 3
        if: ${{ startsWith(matrix.scala, '3.') }}
        run: free --si -tmws 10 & ./sbt ++${{ matrix.scala }} root3/Test/compile

  publishLocal:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.11.*', '2.12.*', '2.13.*', '3.*']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: publishLocal 2.11
        if: ${{ startsWith(matrix.scala, '2.11.') }}
        run: ./sbt ++${{ matrix.scala }} root211/publishLocal
      - name: publishLocal 2.12
        if: ${{ startsWith(matrix.scala, '2.12.') }}
        run: ./sbt ++${{ matrix.scala }} root212/publishLocal
      - name: publishLocal 2.13
        if: ${{ startsWith(matrix.scala, '2.13.') }}
        run: ./sbt ++${{ matrix.scala }} root213/publishLocal
      - name: publishLocal 3
        if: ${{ startsWith(matrix.scala, '3.') }}
        run: ./sbt ++${{ matrix.scala }} root3/publishLocal

  website:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Check Website Generation
        run: |
          ./scripts/createSite.sh ${{ github.ref }}
        
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.11.12', '2.12.17', '2.13.10', '3.2.0']
        java: ['17']
        platform: ['JVM']
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.2
    - name: Setup Java
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Mima Checks
      if: ${{ !startsWith(matrix.scala, '3.') }}
      run: ./sbt ++${{ matrix.scala }}! mimaChecks
    - name: Test 2.11
      if: ${{ startsWith(matrix.scala, '2.11.') }}
      run: ./sbt ++${{ matrix.scala }}! root${{ matrix.platform }}211/test
    - name: Test 2.12
      if: ${{ startsWith(matrix.scala, '2.12.') }}
      run: ./sbt ++${{ matrix.scala }}! root${{ matrix.platform }}212/test
    - name: Test 2.13
      if: ${{ startsWith(matrix.scala, '2.13.') }}
      run: ./sbt ++${{ matrix.scala }}! root${{ matrix.platform }}213/test
    - name: Test 3
      if: ${{ startsWith(matrix.scala, '3.') }}
      run: ./sbt ++${{ matrix.scala }}! root${{ matrix.platform }}3/test

  testJvms:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11']
        platform: ['JVM']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Test on different JVM versions
        run: ./sbt root${{ matrix.platform }}/test

  testPlatforms:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
        platform: ['JS', 'Native']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 9
      - name: Test on different Scala target platforms
        run: free --si -tmws 10 & ./sbt root${{ matrix.platform }}/test

  ci:
    runs-on: ubuntu-20.04
    needs: [lint, compile, publishLocal, website, test, testJvms, testPlatforms]
    steps:
      - name: Aggregate of lint, mdoc and all tests
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Release
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
