name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx3G # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx3G # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.0
    - name: Setup Java
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 17
        check-latest: true
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Lint code
      run: ./sbt check

  compile:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check generation of ScalaDoc
        run: ./sbt +Test/compile

  publishLocal:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check that building packages works
        run: ./sbt +publishLocal

  website:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check Website Generation
        run: ./sbt docs/docusaurusCreateSite
        
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.11.12', '2.12.15', '2.13.8', '3.1.1']
        platform: ['JVM']
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.0
    - name: Setup Java
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 17
        check-latest: true
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Mima Checks
      if: ${{ !startsWith(matrix.scala, '3.') }}
      run: ./sbt ++${{ matrix.scala }}! mimaChecks
    - name: Test 2.11.x
      if: ${{ startsWith(matrix.scala, '2.11.') }}
      run: ./sbt ++${{ matrix.scala }}! test${{ matrix.platform }}211
    - name: Test 2.12.x and 2.13.x
      if: ${{ !startsWith(matrix.scala, '2.11.') && !startsWith(matrix.scala, '3.') }}
      run: ./sbt ++${{ matrix.scala }}! test${{ matrix.platform }}
    - name: Test 3.x
      if: ${{ startsWith(matrix.scala, '3.') }}
      run: ./sbt ++${{ matrix.scala }}! test${{ matrix.platform }}Dotty

  testJvms:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11']
        platform: ['JVM']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Test on different JVM versions
        run: ./sbt test${{ matrix.platform }}

  testPlatforms:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform: ['JS', 'Native']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Test on different Scala target platforms
        run: ./sbt test${{ matrix.platform }}

  ci:
    runs-on: ubuntu-20.04
    needs: [lint, compile, publishLocal, website, test, testJvms, testPlatforms]
    steps:
      - name: Aggregate of lint, mdoc and all tests
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Release
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
