name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx3G # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx3G # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'series/2.x'
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2.3.4
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v13
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Lint code
      run: ./sbt check

  compile:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check generation of ScalaDoc
        run: ./sbt +Test/compile

  publishLocal:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check that building packages works
        run: ./sbt +publishLocal

  website:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check Website Generation
        run: |
          ./sbt docs/mdoc
          cd website
          mv version2-only-docusaurus.config.js docusaurus.config.js 
          rm -f versions.json
          yarn install 
          yarn build 
          cd ..
        
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['8']
        scala: ['2.11.12', '2.12.14', '2.13.6', '3.0.2']
        platform: ['JVM']
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2.3.4
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v13
      with:
        java-version: ${{ matrix.java }}
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Mima Checks
      if: ${{ !startsWith(matrix.scala, '3.0.') }}
      run: ./sbt ++${{ matrix.scala }}! mimaChecks
    - name: Test 2.11.x
      if: ${{ startsWith(matrix.scala, '2.11.') }}
      run: ./sbt ++${{ matrix.scala }}! test${{ matrix.platform }}211
    - name: Test 2.12.x and 2.13.x
      if: ${{ !startsWith(matrix.scala, '2.11.') && !startsWith(matrix.scala, '3.0.') }}
      run: ./sbt ++${{ matrix.scala }}! test${{ matrix.platform }}
    - name: Test 3.x
      if: ${{ startsWith(matrix.scala, '3.0.') }}
      run: ./sbt ++${{ matrix.scala }}! test${{ matrix.platform }}Dotty

  testJvms:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17']
        platform: ['JVM']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Test on different JVM versions
        run: ./sbt test${{ matrix.platform }}

  testPlatforms:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: ['8']
        platform: ['JS', 'Native']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Test on different Scala target platforms
        run: ./sbt test${{ matrix.platform }}

  ci:
    runs-on: ubuntu-20.04
    needs: [lint, compile, publishLocal, website, test, testJvms, testPlatforms]
    steps:
      - name: Aggregate of lint, mdoc and all tests
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Release
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
