name: Website

on:
  push:
    branches:
      - documentation

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - run: |
          ./scripts/createSite.sh ${{ github.ref }}
      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build