name: Website

on:
  push:
    branches:
      - documentation

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - run: |
          ./scripts/createSite.sh ${{ github.ref }}
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.microsite }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          cd website 
          git config --global user.email "ci@ziverge.com"
          git config --global user.name "GH Actions Site"
          yarn deploy