name: Website

on:
  push:
    branches:
      - series/2.x
    tags:
      - docs.*

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - run: |
          ./scripts/createSite.sh ${{ github.ref }}
      - name: Release to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./website/build
