name: Website

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Publish Github pages
        run: |
          set -x 
          cd website
          yarn install
          npx tailwind --input src/css/index.css --output static/css/tailwind.css
          cd ..
          ./sbt docs/docusaurusPublishGhpages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
